### PR TITLE
updated version of bindgen

### PR DESCRIPTION
**Pull request by hartmut**
Version in the current master branch didn't work on ubuntu 16.04 and current rust compiler. It created "undefined reference to" errors.

### CODE REVIEW

**Comment by fitzgen** [comment]
Thanks!
